# Generated by Django 3.1.5 on 2021-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_auto_20211202_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default='9830559192', max_length=15),
        ),
    ]
