# Generated by Django 4.0 on 2021-12-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
