# Generated by Django 4.0 on 2021-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degrees',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
