# Generated by Django 4.0 on 2021-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_doctor_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(default='-'),
        ),
    ]
