# Generated by Django 4.0 on 2021-12-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_alter_doctor_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='profilePic/'),
        ),
    ]
