# Generated by Django 4.0 on 2021-12-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_doctor_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dislikes',
            field=models.ManyToManyField(related_name='doctor_dislikes', to='account_app.Patient'),
        ),
    ]
