# Generated by Django 4.0 on 2022-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_doctor_doctor_reg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='degreeCertificate/'),
        ),
    ]
