# Generated by Django 4.0 on 2022-01-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0017_doctor_degree_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
