# Generated by Django 4.0 on 2022-01-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0022_doctor_unique_doctor_reg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='chamber_address',
            field=models.TextField(default=''),
        ),
    ]
