# Generated by Django 4.0 on 2021-12-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0011_doctor_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField()),
                ('a_time', models.TimeField()),
                ('p_first_name', models.CharField(max_length=100)),
                ('p_middle_name', models.CharField(max_length=100)),
                ('p_last_name', models.CharField(max_length=100)),
                ('p_gender', models.CharField(max_length=10)),
                ('p_contact_no', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_age', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.doctor')),
            ],
            options={
                'unique_together': {('a_date', 'a_time')},
            },
        ),
    ]
