# Generated by Django 4.0 on 2021-12-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_doctor_bio'),
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('a_date', 'a_time', 'doctor')},
        ),
    ]
