# Generated by Django 4.0 on 2021-12-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_alter_appointment_a_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='p_age',
            field=models.IntegerField(default=0),
        ),
    ]
