# Generated by Django 4.0 on 2021-12-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_alter_doctor_degrees'),
        ('patient_app', '0006_alter_appointment_p_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account_app.patient'),
        ),
    ]
