# Generated by Django 4.0 on 2021-12-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0007_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_reason',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
