# Generated by Django 4.0 on 2021-12-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0008_appointment_visit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_reason',
            field=models.CharField(max_length=50),
        ),
    ]
