# Generated by Django 4.0 on 2021-12-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_doctor_dislikes'),
        ('patient_app', '0012_alter_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account_app.patient'),
        ),
    ]
