# Generated by Django 4.0 on 2021-12-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0013_reviews_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
