# Generated by Django 4.0 on 2022-01-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0016_alter_appointment_a_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('a_date', 'a_time', 'doctor'), name='unique_appointment_key'),
        ),
    ]
