# Generated by Django 4.0 on 2021-12-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
