# Generated by Django 4.0 on 2021-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_specialization_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='imagesSpl/'),
        ),
    ]
