# Generated by Django 4.0 on 2021-12-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_specialization_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('userid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
    ]
